---
version: 2

registries:

  coop-ghcr:
    type: docker-registry
    url: ghcr.io
    username: CoopGithubServiceaccount
    password: ${{ secrets.DEPENDABOT_GHCR_PULL }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/devtools"
    schedule:
      interval: "daily"
    registries:
      - coop-ghcr
    groups:
      devtools:
        patterns:
          - coopnorge/engineering-docker-images/e0/*
